import { randomBytes } from 'node:crypto';

export type ServerEnv = Record<string, string | undefined>;

const MIN_SESSION_SECRET_BYTES = 32;
const DEFAULT_PIN_MIN_LENGTH = 4;
const MAX_PIN_LENGTH = 12;
const RECOMMENDED_PIN_LENGTH = 6;

const trimmed = (value: string | undefined) => value?.trim() || '';

/**
 * Lists every reason the production configuration is unsafe, so one failed
 * boot tells the operator everything that has to be fixed.
 */
export function validateProductionConfig(env: ServerEnv): string[] {
  const problems: string[] = [];
  const sessionSecret = trimmed(env.APP_SESSION_SECRET);
  const pinHash = trimmed(env.APP_PIN_HASH);
  const accessKey = trimmed(env.APP_ACCESS_KEY);

  if (!sessionSecret) {
    problems.push('APP_SESSION_SECRET is not set. Generate one with `openssl rand -base64 48`.');
  } else if (Buffer.byteLength(sessionSecret, 'utf8') < MIN_SESSION_SECRET_BYTES) {
    problems.push(`APP_SESSION_SECRET must be at least ${MIN_SESSION_SECRET_BYTES} bytes.`);
  }

  if (!pinHash && accessKey) {
    problems.push('APP_ACCESS_KEY (plaintext PIN) is no longer accepted in production. Set APP_PIN_HASH with `npm run pin:hash` and remove APP_ACCESS_KEY.');
  } else if (!pinHash) {
    problems.push('APP_PIN_HASH is not set. Generate one with `npm run pin:hash -- <PIN>`.');
  } else if (!pinHash.startsWith('pbkdf2$')) {
    problems.push('APP_PIN_HASH must be a pbkdf2$ hash generated by `npm run pin:hash`.');
  }

  return problems;
}

/** Refuses to boot a production server with unsafe authentication defaults. */
export function assertProductionConfig(
  env: ServerEnv,
  { exit, log }: { exit: (code: number) => void; log: (...messages: unknown[]) => void },
) {
  if (env.NODE_ENV !== 'production') return;
  const problems = validateProductionConfig(env);
  if (problems.length === 0) return;
  log('Refusing to start: unsafe production configuration.');
  problems.forEach(problem => log(`  - ${problem}`));
  exit(1);
}

export type SessionSecrets = { current: string; previous?: string; ephemeral: boolean };

/**
 * Only APP_SESSION_SECRET signs sessions. Without it (development only, since
 * production refuses to boot) a random per-process key is used, so restarting
 * the dev server signs everyone out instead of accepting forgeable tokens.
 */
export function resolveSessionSecrets(
  env: ServerEnv,
  { warn = console.warn }: { warn?: (...messages: unknown[]) => void } = {},
): SessionSecrets {
  const previous = trimmed(env.APP_SESSION_SECRET_PREVIOUS) || undefined;
  const current = trimmed(env.APP_SESSION_SECRET);
  if (current) return { current, previous, ephemeral: false };

  warn('APP_SESSION_SECRET is not set; using a random key. Sessions end whenever the server restarts.');
  return { current: randomBytes(48).toString('base64'), previous, ephemeral: true };
}

export function resolveOwnerPinSecret(env: ServerEnv): { secret: string; usingDevDefault: boolean } {
  const pinHash = trimmed(env.APP_PIN_HASH);
  if (pinHash) return { secret: pinHash, usingDevDefault: false };
  const legacyKey = trimmed(env.APP_ACCESS_KEY);
  if (legacyKey) return { secret: legacyKey, usingDevDefault: false };
  // Production refuses to boot without APP_PIN_HASH, so this is development only.
  return { secret: '0000', usingDevDefault: true };
}

export function resolvePinMinLength(env: ServerEnv): number {
  const value = Number(trimmed(env.PIN_MIN_LENGTH));
  if (!Number.isInteger(value) || value < DEFAULT_PIN_MIN_LENGTH || value > MAX_PIN_LENGTH) {
    return DEFAULT_PIN_MIN_LENGTH;
  }
  return value;
}

export type PinInputClassification =
  | { ok: true; upgradeRequired: boolean }
  | { ok: false; error: string };

export function classifyPinInput(key: string, minLength: number): PinInputClassification {
  if (!new RegExp(`^\\d{${minLength},${MAX_PIN_LENGTH}}$`).test(key)) {
    return { ok: false, error: `PIN은 ${minLength}~${MAX_PIN_LENGTH}자리 숫자여야 합니다.` };
  }
  return { ok: true, upgradeRequired: key.length < RECOMMENDED_PIN_LENGTH };
}
