/**
 * Finds transactions the user keeps re-entering by hand, so the app can offer
 * to turn them into a one-tap quick entry instead of making them retype it.
 */

import { QuickEntry, Transaction } from '../types';

export interface QuickEntrySuggestion {
  merchant: string;
  categoryId: string;
  type: 'income' | 'expense';
  /** How many times this shape appeared inside the lookback window. */
  count: number;
  /** Set when every occurrence cost the same, which makes a one-tap chip. */
  fixedAmount: number | null;
  /** Most recent amount, used as the prefill when the amount varies. */
  latestAmount: number;
  lastUsedDate: string;
}

export interface SuggestionOptions {
  /** Occurrences needed before a shape counts as a habit. */
  minimumCount?: number;
  /** Days of history to consider. */
  lookbackDays?: number;
  /** Cap on how many suggestions to return. */
  limit?: number;
  today?: Date;
}

const DEFAULTS = { minimumCount: 3, lookbackDays: 90, limit: 3 };

function normalizeMerchant(merchant: string): string {
  return merchant.trim().toLowerCase();
}

function shiftDays(date: Date, days: number): string {
  const shifted = new Date(date.getFullYear(), date.getMonth(), date.getDate() - days);
  const month = `${shifted.getMonth() + 1}`.padStart(2, '0');
  const day = `${shifted.getDate()}`.padStart(2, '0');
  return `${shifted.getFullYear()}-${month}-${day}`;
}

/**
 * A transaction only suggests a habit when the user typed it themselves. Card
 * settlements, installment rounds and anything already driven by a recurring
 * template are generated by the app, so repeating them proves nothing.
 */
function isHabitCandidate(transaction: Transaction): boolean {
  if (transaction.merchant.trim() === '') return false;
  if (transaction.recurringTemplateId) return false;
  if (transaction.role && transaction.role !== 'normal') return false;
  return transaction.installment == null;
}

export function suggestQuickEntryCandidates(
  transactions: Transaction[],
  existingEntries: QuickEntry[] = [],
  options: SuggestionOptions = {},
): QuickEntrySuggestion[] {
  const { minimumCount, lookbackDays, limit } = { ...DEFAULTS, ...options };
  const since = shiftDays(options.today ?? new Date(), lookbackDays);

  const alreadySaved = new Set(
    existingEntries.map(entry => `${normalizeMerchant(entry.merchant)}::${entry.categoryId}`),
  );

  const groups = new Map<string, Transaction[]>();
  transactions
    .filter(transaction => transaction.localDate >= since && isHabitCandidate(transaction))
    .forEach(transaction => {
      const key = `${normalizeMerchant(transaction.merchant)}::${transaction.categoryId}`;
      if (alreadySaved.has(key)) return;
      const bucket = groups.get(key);
      if (bucket) bucket.push(transaction);
      else groups.set(key, [transaction]);
    });

  const suggestions: QuickEntrySuggestion[] = [];
  groups.forEach(bucket => {
    if (bucket.length < minimumCount) return;
    const byDateDesc = [...bucket].sort((left, right) => right.localDate.localeCompare(left.localDate));
    const newest = byDateDesc[0];
    const amounts = new Set(bucket.map(transaction => transaction.amount));

    suggestions.push({
      merchant: newest.merchant.trim(),
      categoryId: newest.categoryId,
      type: newest.type,
      count: bucket.length,
      fixedAmount: amounts.size === 1 ? newest.amount : null,
      latestAmount: newest.amount,
      lastUsedDate: newest.localDate,
    });
  });

  return suggestions
    .sort((left, right) => (
      right.count - left.count || right.lastUsedDate.localeCompare(left.lastUsedDate)
    ))
    .slice(0, limit);
}
