import { App } from '@capacitor/app';
import { registerPlugin } from '@capacitor/core';
import { BudgetAlertLevel, UserProfile, WidgetPrivacyMode } from '../types';
import { isNativeAndroid } from './platform';

/**
 * A quick entry as the home-screen widget sees it.
 *
 * Deliberately not the whole record: the widget renders on a lock screen that
 * anyone can look at, so it carries the label and the amount it will record and
 * nothing about where the money goes.
 */
export interface WidgetQuickEntry {
  id: string;
  label: string;
  /** `null` means the app has to ask for the amount after the tap. */
  amount: number | null;
}

/** Chips beyond this do not fit any widget size worth rendering. */
export const MAX_WIDGET_QUICK_ENTRIES = 4;

export interface WidgetSnapshotV1 {
  schemaVersion: 1;
  periodYM: string;
  periodEndDate: string;
  remainingAllowance: number;
  confirmedVariableExpenses: number;
  spendableLimit: number;
  dailySafeAllowance: number;
  daysRemaining: number;
  alertLevel: BudgetAlertLevel;
  calculatedAt: string;
  visibleUntil: string | null;
  privacyMode: WidgetPrivacyMode;
  quickEntries: WidgetQuickEntry[];
}
interface WidgetBridgePlugin {
  publishSnapshot(options: { snapshot: WidgetSnapshotV1 }): Promise<void>;
  setLocked(options: { locked: boolean }): Promise<void>;
  requestPin(): Promise<{ supported: boolean; requested: boolean }>;
  refresh(): Promise<void>;
}

const WidgetBridge = registerPlugin<WidgetBridgePlugin>('WidgetBridge');

export interface WidgetSummarySource {
  remainingAllowance: number;
  confirmedVariableExpenses: number;
  spendableLimit: number;
  dailySafeAllowance: number;
  daysRemaining: number;
  alertLevel: BudgetAlertLevel;
}

export function normalizeWidgetPrivacyMode(value: unknown): WidgetPrivacyMode {
  return value === 'always_show' || value === 'amounts_hidden' ? value : 'unlock_required';
}

export function buildWidgetSnapshot(
  periodYM: string,
  periodEndDate: string,
  summary: WidgetSummarySource,
  profile: Pick<UserProfile, 'idleLockMinutes' | 'widgetPrivacyMode'>,
  now = new Date(),
  quickEntries: WidgetQuickEntry[] = [],
): WidgetSnapshotV1 {
  const idleMinutes = Number(profile.idleLockMinutes);
  const visibleUntil = normalizeWidgetPrivacyMode(profile.widgetPrivacyMode) === 'unlock_required'
    && Number.isFinite(idleMinutes)
    && idleMinutes > 0
    ? new Date(now.getTime() + idleMinutes * 60_000).toISOString()
    : null;

  return {
    schemaVersion: 1,
    periodYM,
    periodEndDate,
    remainingAllowance: Math.round(summary.remainingAllowance),
    confirmedVariableExpenses: Math.round(summary.confirmedVariableExpenses),
    spendableLimit: Math.round(summary.spendableLimit),
    dailySafeAllowance: Math.round(summary.dailySafeAllowance),
    daysRemaining: Math.max(0, Math.trunc(summary.daysRemaining)),
    alertLevel: summary.alertLevel,
    calculatedAt: now.toISOString(),
    visibleUntil,
    privacyMode: normalizeWidgetPrivacyMode(profile.widgetPrivacyMode),
    quickEntries: quickEntries.slice(0, MAX_WIDGET_QUICK_ENTRIES).map(entry => ({
      id: entry.id,
      label: entry.label,
      amount: entry.amount === null ? null : Math.round(entry.amount),
    })),
  };
}

let lastPublishedSnapshot = '';

export async function publishWidgetSnapshot(snapshot: WidgetSnapshotV1): Promise<void> {
  if (!isNativeAndroid()) return;
  const serialized = JSON.stringify(snapshot);
  if (serialized === lastPublishedSnapshot) return;
  await WidgetBridge.publishSnapshot({ snapshot });
  lastPublishedSnapshot = serialized;
}

export async function setWidgetLocked(locked: boolean): Promise<void> {
  if (!isNativeAndroid()) return;
  await WidgetBridge.setLocked({ locked });
  if (locked) lastPublishedSnapshot = '';
}

export async function requestWidgetPin(): Promise<{ supported: boolean; requested: boolean }> {
  if (!isNativeAndroid()) return { supported: false, requested: false };
  return WidgetBridge.requestPin();
}

export async function refreshWidgets(): Promise<void> {
  if (!isNativeAndroid()) return;
  await WidgetBridge.refresh();
}

export type NativeDestination =
  | { kind: 'home' }
  | { kind: 'transaction/new' }
  | { kind: 'settings/widget' }
  | { kind: 'quick-entry'; quickEntryId: string };

/** Quick entry ids are generated by saveQuickEntry; nothing else is accepted. */
const QUICK_ENTRY_ID = /^quick_[A-Za-z0-9_]+$/;

/**
 * Turns a widget deep link into an in-app destination.
 *
 * The allow-list is exhaustive on purpose. A link arriving from outside the app
 * must never be able to name an arbitrary action, so anything unrecognised
 * resolves to null rather than to a best guess.
 */
export function parseNativeDestination(url: string): NativeDestination | null {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'expendbreak:') return null;
    const destination = `${parsed.host}${parsed.pathname}`.replace(/^\/+|\/+$/g, '');

    if (destination === 'home') return { kind: 'home' };
    if (destination === 'transaction/new') return { kind: 'transaction/new' };
    if (destination === 'settings/widget') return { kind: 'settings/widget' };

    const quickEntryMatch = /^quick\/(.+)$/.exec(destination);
    if (quickEntryMatch && QUICK_ENTRY_ID.test(quickEntryMatch[1])) {
      return { kind: 'quick-entry', quickEntryId: quickEntryMatch[1] };
    }
    return null;
  } catch {
    return null;
  }
}

export async function subscribeToNativeDestinations(
  listener: (destination: NativeDestination) => void,
): Promise<() => void> {
  if (!isNativeAndroid()) return () => undefined;

  const launch = await App.getLaunchUrl();
  const initialDestination = launch?.url ? parseNativeDestination(launch.url) : null;
  if (initialDestination) listener(initialDestination);

  const handle = await App.addListener('appUrlOpen', ({ url }) => {
    const destination = parseNativeDestination(url);
    if (destination) listener(destination);
  });
  return () => void handle.remove();
}
