import { describe, expect, it } from 'vitest';
import { buildWidgetSnapshot, normalizeWidgetPrivacyMode, parseNativeDestination } from './widget';

const summary = {
  remainingAllowance: 1_020_000.4,
  confirmedVariableExpenses: 299_999.6,
  spendableLimit: 1_320_000,
  dailySafeAllowance: 35_172.2,
  daysRemaining: 29,
  alertLevel: 'safe' as const,
};

describe('widget snapshot', () => {
  it('publishes only the minimum rounded summary with an idle expiry', () => {
    const now = new Date('2026-08-13T03:00:00.000Z');
    expect(buildWidgetSnapshot('2026-08', '2026-09-09', summary, {
      idleLockMinutes: 30,
      widgetPrivacyMode: 'unlock_required',
    }, now)).toEqual({
      schemaVersion: 1,
      periodYM: '2026-08',
      periodEndDate: '2026-09-09',
      remainingAllowance: 1_020_000,
      confirmedVariableExpenses: 300_000,
      spendableLimit: 1_320_000,
      dailySafeAllowance: 35_172,
      daysRemaining: 29,
      alertLevel: 'safe',
      calculatedAt: '2026-08-13T03:00:00.000Z',
      visibleUntil: '2026-08-13T03:30:00.000Z',
      privacyMode: 'unlock_required',
      quickEntries: [],
    });
  });

  it('does not expire explicit always-show widgets', () => {
    const snapshot = buildWidgetSnapshot('2026-08', '2026-09-09', summary, {
      idleLockMinutes: 30,
      widgetPrivacyMode: 'always_show',
    }, new Date('2026-08-13T03:00:00.000Z'));
    expect(snapshot.visibleUntil).toBeNull();
  });

  it('defaults unknown privacy values to unlock-required', () => {
    expect(normalizeWidgetPrivacyMode(undefined)).toBe('unlock_required');
    expect(normalizeWidgetPrivacyMode('unexpected')).toBe('unlock_required');
  });
});
describe('native widget destinations', () => {
  it.each([
    ['expendbreak://home', 'home'],
    ['expendbreak://transaction/new', 'transaction/new'],
    ['expendbreak://settings/widget', 'settings/widget'],
  ])('parses %s', (url, expected) => {
    expect(parseNativeDestination(url)).toEqual({ kind: expected });
  });

  it('parses a quick entry link into the id it names', () => {
    expect(parseNativeDestination('expendbreak://quick/quick_123_ab4c')).toEqual({
      kind: 'quick-entry',
      quickEntryId: 'quick_123_ab4c',
    });
  });

  it('rejects a quick entry id that was not generated by the app', () => {
    expect(parseNativeDestination('expendbreak://quick/../../etc')).toBeNull();
    expect(parseNativeDestination('expendbreak://quick/tx_1')).toBeNull();
    expect(parseNativeDestination('expendbreak://quick/')).toBeNull();
  });

  it('rejects external and mutating destinations', () => {
    expect(parseNativeDestination('https://example.com')).toBeNull();
    expect(parseNativeDestination('expendbreak://transaction/delete/1')).toBeNull();
  });
});

describe('widget quick entries', () => {
  it('caps the published chips and rounds their amounts', () => {
    const chips = Array.from({ length: 6 }, (_, index) => ({
      id: `quick_${index}`,
      label: `칩 ${index}`,
      amount: 1000.6,
    }));
    const snapshot = buildWidgetSnapshot('2026-08', '2026-09-09', summary, {
      idleLockMinutes: 30,
      widgetPrivacyMode: 'always_show',
    }, new Date('2026-08-13T03:00:00.000Z'), chips);

    expect(snapshot.quickEntries).toHaveLength(4);
    expect(snapshot.quickEntries[0].amount).toBe(1001);
  });

  it('keeps a variable-amount chip null rather than zeroing it', () => {
    const snapshot = buildWidgetSnapshot('2026-08', '2026-09-09', summary, {
      idleLockMinutes: 30,
      widgetPrivacyMode: 'always_show',
    }, new Date('2026-08-13T03:00:00.000Z'), [
      { id: 'quick_1', label: '점심', amount: null },
    ]);

    expect(snapshot.quickEntries[0].amount).toBeNull();
  });
});
